from app.service.api.v1.artisan_use_letter.extract_v1 import AULDataPointExtractorV1
from app.service.api.v1.broker_package.extract_v1 import BrokerPackageDataPointExtractorV1
from app.service.api.v1.crm_receipt.extract_v1 import CRMDataPointExtractorV1
from app.service.api.v1.driving_license.extract_v1 import DLDataPointExtractorV1
from app.service.api.v1.eft.extract_v1 import EFTDataPointExtractorV1
from app.service.api.v1.insurance_application.extract_v1 import APPDataPointExtractorV1
from app.service.api.v1.insurance_application.verify_v1 import DataPointVerifierV1
from app.service.api.v1.itc.extract_v1 import ITCDataPointExtractorV1
from app.service.api.v1.mvr.extract_v1 import MVRDataPointExtractorV1
from app.service.api.v1.pleasure_use_letter.extract_v1 import PULDataPointExtractorV1
from app.service.api.v1.promise_to_provide.extract_v1 import PTPDataPointExtractorV1
from app.service.api.v1.registration.extract_v1 import REGDataPointExtractorV1
from app.service.api.v1.same_person_statement.extract_v1 import SPSDataPointExtractorV1
from app.service.api.v1.stripe_receipt.extract_v1 import STRPDataPointExtractorV1
from app.service.api.v1.vr.extract_v1 import VRDataPointExtractorV1
from app.service.api.v1.non_owners_letter.extract_v1 import NOLDataPointExtractorV1
