version: "3.4"

services:
  demo_site:
    build:
      context: .
      dockerfile: demo_site.Dockerfile
    volumes:
      - "/mnt/user-data:/mnt/user-data:rw"
    environment:
      Tesseract_PATH: "/usr/bin/tesseract"
      USER_DATA_PATH: "/mnt/user-data"
      S3_ENCRYPTION_KEY: "Binary Encryption Key"
    ports:
      - "8081:8081"

  underwriting_automation:
    build:
      context: ../POCs/underwriting-automation
      dockerfile: underwriting_automation.Dockerfile
    volumes:
      - "/mnt/user-data:/mnt/user-data:rw"
    environment:
      Tesseract_PATH: "/usr/bin/tesseract"
      S3_ENCRYPTION_KEY: "Binary Encryption Key"
    ports:
      - "8000:8000"

  answering_machine_detection:
    build:
      context: ../POCs/answering-machine-detection
      dockerfile: amd.Dockerfile
    volumes:
      - "/mnt/user-data:/mnt/user-data:rw"
    environment:
      S3_ENCRYPTION_KEY: "Binary Encryption Key"
    ports:
      - "8082:8082"